version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root directory where your package.json is located
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "react"
        versions: ["19.x"] # Optional: avoid major updates for stability
      - dependency-name: "next"
        versions: ["15.x"]
