# .github/FUNDING.yml

# github: [] # Add your GitHub sponsor username if/when available
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
buy_me_a_coffee: 'IamJP' # ✅ Active support via Buy Me a Coffee
thanks_dev:
custom: ['https://www.buymeacoffee.com/IamJP'] # Optional custom link
